# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c0943780dc299003dfd4e67f03a03acd"
name = "7n-shop-adminlive"
application_url = "https://sevennshopadminlive-uq5r.onrender.com"
embedded = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_discounts,read_orders,read_price_rules,read_products,write_customers,write_discounts,write_orders,write_price_rules,write_products,write_themes,read_themes,write_content,read_content,write_pixels,read_pixels,read_customer_events"

optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://sevennshopadminlive-uq5r.onrender.com/auth/callback",
  "https://sevennshopadminlive-uq5r.onrender.com/auth/shopify/callback",
  "https://sevennshopadminlive-uq5r.onrender.com/api/auth"
]

[app_proxy]
url = "https://sevennshopadminlive-uq5r.onrender.com/app/custom-proxy"
subpath = "public"
prefix = "apps"


[[webhooks.subscriptions]]
  topics = [ "orders/cancelled", "checkouts/update", "orders/create" ]
  uri = "/webhooks/orders/create"

  [[webhooks.subscriptions]]
  topics = [ "customers/create", "customers/update" ]
  uri = "/webhookscutomer"