import { authenticate } from "../shopify.server";
import db from "../db.server";
import { updateCleverTapWallet, sendCleverTapEvent, processPendingToActive } from "../utils/clevertap.server";

export const action = async ({ request }) => {
  const { admin, topic, shop, payload } = await authenticate.webhook(request);

  console.log(`\n🔔 WEBHOOK: ${topic} | SHOP: ${shop}\n`);

  const shopifyOrderId = payload.admin_graphql_api_id || `gid://shopify/Order/${payload.id}`;
  const readableOrderNumber = payload.name || String(payload.order_number);
  const customerIdString = payload.customer ? String(payload.customer.id).trim() : "";
  const customerEmail = payload.customer ? payload.customer.email : "";
  const ctIdentity = customerEmail ? customerEmail.trim() : String(customerIdString).trim();
  const settings = await db.userbirthday.findFirst({ where: { shop: shop } });
  const ratio = settings?.earnPercentage || 10;

  if (topic === "ORDERS_CREATE" || topic === "orders/create") {
    const orderTotal = Math.floor(parseFloat(payload.total_price || "0"));
    const discountUsed = Math.floor(parseFloat(payload.total_discounts || "0"));
    const subtotalPrice = parseFloat(payload.total_line_items_price || "0");
    let pointsEarnedForHistory = 0;
    let highRewardPointForHistory = 0;
    let usedCouponCode = null;
    if (payload.discount_applications?.length > 0) {
      usedCouponCode = payload.discount_applications[0].title || payload.discount_applications[0].code;
    }
    const cleanCouponCode = usedCouponCode ? String(usedCouponCode).trim() : "";
    const isAutoGeneratedReward = cleanCouponCode.startsWith("REWARD-");
    try {
      const settings = await db.userbirthday.findFirst({ where: { shop: shop } });
        const THRESHOLD = settings?.minOrderTotal || 10000;
        const FIXED_REWARD = settings?.fixedRewardPoint || 100;
      // 1. SABSE PEHLE: Reward record dhoondo ya naya banao (Foreign Key Error fix)
      let existingReward = await db.rewardpoint.findFirst({
        where: { customerid: customerIdString, store: shop },
      });

      if (!existingReward) {
        existingReward = await db.rewardpoint.create({
          data: { 
            customerid: customerIdString, store: shop, 
            pointvalue: 0, activepoint: 0, pendingpoint: 0, 
            customeremail: customerEmail 
          },
        });
      }
      
      const currentRewardPointId = existingReward.id;
      // --- B. INSTANT EARN LOGIC (For 10,000+ Orders) ---
        if (orderTotal >= THRESHOLD) {
            pointsEarnedForHistory = FIXED_REWARD;
            highRewardPointForHistory = FIXED_REWARD;
            console.log(`🚀 [INSTANT CREDIT] High Value Order! Adding ${pointsEarnedForHistory} points.`);

            // ✅ DB Update: Direct increment in activepoint & pointvalue (No delay)
            await db.rewardpoint.update({
                where: { id: currentRewardPointId },
                data: { 
                    activepoint: { increment: highRewardPointForHistory },
                    pointvalue: { increment: highRewardPointForHistory }
                },
            });

            // ✅ CleverTap: Instant Credit API
            await updateCleverTapWallet(
                ctIdentity, 
                pointsEarnedForHistory, 
                "CREDIT", 
                readableOrderNumber, 
                orderTotal, 
                `High Value Reward #${readableOrderNumber}`, 
                shop, 
                "ACTIVE"
            );

              await sendCleverTapEvent(ctIdentity, "Points Activated", {
              "Points": pointsEarnedForHistory, 
              "Order_ID": readableOrderNumber,
              "Type": "High Value Order"
            }, shop); // <-- Passing shop
        }

      // 2. FIRST ORDER CHECK: History dhoondo
      const previousOrderCount = await db.orderHistory.count({ 
        where: { rewardPointId: currentRewardPointId } 
      });
      const isFirstOrder = (previousOrderCount === 0);

      // ----------------------------------------------------
      // A. REDEEM LOGIC: Jab Discount Code Apply ho (Debit)
      // ----------------------------------------------------
      if (discountUsed > 0 && isAutoGeneratedReward) {
        console.log(`🎫 [REDEEM] Deducting ${discountUsed} points...`);

        // DB Update: pointvalue and activepoint deduct karo
        await db.rewardpoint.update({
          where: { id: currentRewardPointId },
          data: { 
            pointvalue: { decrement: Math.min(discountUsed, existingReward.pointvalue) },
            activepoint: { decrement: Math.min(discountUsed, existingReward.activepoint) }
          },
        });

        // CleverTap Debit API
        await updateCleverTapWallet(ctIdentity, discountUsed, "DEBIT", readableOrderNumber, orderTotal, `Redeemed for #${readableOrderNumber}`, shop, "ACTIVE");
        await sendCleverTapEvent(ctIdentity, "Points Redeemed", { "Points": discountUsed, "Order_ID": readableOrderNumber }, shop);     
      }

      // ----------------------------------------------------
      // B. EARN LOGIC: Sirf First Order ke liye (Pending)
      // ----------------------------------------------------
      if (isFirstOrder) {
        //pointsEarnedForHistory = orderTotal;
        pointsEarnedForHistory = Math.floor((orderTotal * ratio) / 100);
        await db.rewardpoint.update({
          where: { id: currentRewardPointId },
          data: { pendingpoint: { increment: pointsEarnedForHistory } },
        });

        // 2 Minute baad active hone ka process
        processPendingToActive(ctIdentity, pointsEarnedForHistory, readableOrderNumber, orderTotal, shop, currentRewardPointId);
         await sendCleverTapEvent(ctIdentity, "Reward Points Pending", {
          "Points": pointsEarnedForHistory, "Order_ID": readableOrderNumber
        }, shop);// <--- PASS SHOP HERE TOO
      }

      // ----------------------------------------------------
      // C. SAVE HISTORY & DELETE DISCOUNT
      // ----------------------------------------------------
      let allProductNames = payload.line_items ? payload.line_items.map(item => item.name).join(", ") : "";
      await db.orderHistory.create({
        data: {
          orderId: shopifyOrderId, orderNumber: readableOrderNumber, productNames: allProductNames,
          discountAmount: discountUsed, couponCode: isAutoGeneratedReward ? cleanCouponCode : null, 
          subtotal: subtotalPrice, pointsEarned: pointsEarnedForHistory, 
          highRewardPoint: highRewardPointForHistory,
          pointsRedeemed: discountUsed, rewardPointId: currentRewardPointId, status: pointsEarnedForHistory > 0 ?"PROCESSED" : "PENDING",// Mark ACTIVE for Cron
        }
      });

      // ----------------------------------------------------
      // 3. DELETE DISCOUNT FROM SHOPIFY
      // ----------------------------------------------------
      if (discountUsed > 0 && admin && isAutoGeneratedReward) {
        try {
          const searchTitle = `REWARD-${customerIdString}`;
          console.log(`🔍 [SHOPIFY] Searching for Discount starting with: ${searchTitle}`);
          const response = await admin.graphql(
            `#graphql
            query FindDiscount($query: String!) {
              discountNodes(first: 10, query: $query) {
                edges {
                  node {
                    id
                    discount {
                      __typename
                      ... on DiscountCodeBasic { title }
                      ... on DiscountAutomaticBasic { title }
                    }
                  }
                }
              }
            }`,
            { variables: { query: `title:${searchTitle}*` } }
          );
          
          const data = await response.json();
          const targetDiscount = data.data?.discountNodes?.edges?.find(e => {
              const title = e.node.discount?.title;
              return title && title.startsWith(searchTitle);
          });
          if (targetDiscount) {
            const discountId = targetDiscount.node.id;
            const discountType = targetDiscount.node.discount.__typename;
            console.log(`🗑️ [SHOPIFY] Found ${discountType}. Deleting ID: ${discountId}`);
            // ✅ FIXED MUTATION: Shopify mein delete karne ka sahi mutation
            const deleteMutation = `#graphql
              mutation discountCodeDelete($id: ID!) {
                discountCodeDelete(id: $id) {
                  deletedCodeDiscountId
                  userErrors { field message }
                }
              }
            `;

            const deleteResponse = await admin.graphql(deleteMutation, { variables: { id: discountId } });
            const deleteData = await deleteResponse.json();
            const deletedId = deleteData.data?.discountCodeDelete?.deletedCodeDiscountId;

            if (deletedId) {
                console.log("✅ [SHOPIFY SUCCESS] Discount Deleted Successfully.");
            } else {
                console.log("⚠️ [SHOPIFY DELETE FAIL]", JSON.stringify(deleteData.data?.discountCodeDelete?.userErrors, null, 2));
            }
          } 
          // if (targetDiscount.length > 0) {
          //   console.log(`🗑️ Found ${targetDiscounts.length} matching discounts. Starting Bulk Delete...`);
            
          //   // 2. Loop chalakar ek-ek karke saare delete karein
          //   const deletePromises = targetDiscounts.map(async (item) => {
          //       const discountId = item.node.id;
          //       const discountTitle = item.node.discount.title;

          //       const deleteMutation = `#graphql
          //         mutation discountCodeDelete($id: ID!) {
          //           discountCodeDelete(id: $id) {
          //             deletedCodeDiscountId
          //             userErrors { field message }
          //           }
          //         }
          //       `;

          //       const deleteResponse = await admin.graphql(deleteMutation, { variables: { id: discountId } });
          //       const deleteData = await deleteResponse.json();
                
          //       if (deleteData.data?.discountCodeDelete?.deletedCodeDiscountId) {
          //           console.log(`✅ [DELETED] ${discountTitle}`);
          //       } else {
          //           console.log(`⚠️ [FAILED] ${discountTitle}:`, JSON.stringify(deleteData.data?.discountCodeDelete?.userErrors));
          //       }
          //   });

          //   // Saare delete operations khatam hone ka intezaar karein
          //   await Promise.all(deletePromises);
          //   console.log("🏁 Bulk delete operation completed.");

          // }
          else {
              console.log("ℹ️ [SHOPIFY] No matching active discount found to delete.");
          }
        } catch (e) { 
          console.error("❌ [SHOPIFY ERROR]", e.message); 
        }
      }
    } catch (error) { console.error("❌ Error:", error); }
  }

// CASE: ORDER CANCELLED (REVERT LOGIC)
else if (topic === "ORDERS_CANCELLED" || topic === "orders/cancelled") {
    console.log("🔴 [ORDER CANCELLED] Processing Revert...");
    try {
     const orderIdToFind = payload.admin_graphql_api_id || `gid://shopify/Order/${payload.id}`;
        const pastOrder = await db.orderHistory.findFirst({
            where: { orderId: orderIdToFind }
        });
        if (!pastOrder) return new Response();
        const userReward = await db.rewardpoint.findFirst({
            where: { customerid: customerIdString, store: shop }
        });
        if (userReward) {
            let pointsToReturn = pastOrder.pointsRedeemed || 0; // Jo customer ne kharche the
            let pointsToRevoke = pastOrder.pointsEarned || 0;   // Jo customer ne earn kiye (High Value points yahan hain)
            // ✅ FIX: pointsRevert mein hum wahi value dalenge jo revert ho rahi hai
            // Agar kharche huye points wapas mil rahe hain toh positive, 
            // Agar earned points wapas liye ja rahe hain toh usse track karein.
            let revertValueForDB = pointsToReturn > 0 ? pointsToReturn : pointsToRevoke;
            await db.rewardpoint.update({
                where: { id: userReward.id },
                data: { 
                    pointvalue: { increment: pointsToReturn - pointsToRevoke },
                    activepoint: { increment: pointsToReturn - pointsToRevoke }
                }
            });
            // ✅ DATABASE UPDATE FIX
            await db.orderHistory.update({
                where: { id: pastOrder.id }, 
                data: { 
                    pointsRevert: revertValueForDB, // Ab yahan 0 nahi aayega
                    status: "CANCELLED" 
                }
            });
            console.log("✅ [DB SUCCESS] User Balance & History Updated.");
            // 3. CleverTap Integration
            let identity = customerEmail ? customerEmail.trim() : String(customerIdString).trim();
            // A. Agar points REDEEM hue the, toh unhe Wallet mein wapas CREDIT karein
            if (pointsToReturn > 0) {
                await updateCleverTapWallet(
                    identity, 
                    pointsToReturn, 
                    "CREDIT", 
                    readableOrderNumber, 
                    0, 
                    `Refund for Cancelled Order #${readableOrderNumber}`, 
                    shop, 
                    "ACTIVE"
                );
            }
            // B. Agar points EARN hue the, toh unhe Wallet se DEBIT (Revoke) karein
            if (pointsToRevoke > 0) {
                await updateCleverTapWallet(
                    identity, 
                    pointsToRevoke, 
                    "DEBIT", 
                    readableOrderNumber, 
                    0, 
                    `Revoked points for Cancelled Order #${readableOrderNumber}`, 
                    shop, 
                    "ACTIVE"
                );
            }
            // C. CleverTap Revert API call (Aapka existing logic)
            // const ctRevertUrl = `https://in1.api.clevertap.com/1/promo/coupons/apply?identity=${encodeURIComponent(identity)}&type=revert`;
            // const revertBody = {
            //     "couponCode": "SHOPIFY_REWARD",
            //     "couponId": 1198,
            //     "order": {
            //         "orderId": readableOrderNumber,
            //         "orderStatus": "reverted",
            //         "saleChannel": "Shopify Webhook"
            //     }
            // };

            // await fetch(ctRevertUrl, {
            //     method: "POST",
            //     headers: { 
            //         "Content-Type": "application/json", 
            //         "X-CleverTap-Account-Id": "ZR5-Z77-557Z", 
            //         "X-CleverTap-Passcode": "GOO-ZMX-UPEL" 
            //     },
            //     body: JSON.stringify(revertBody)
            // });

            // D. Visual Event send karein
            await sendCleverTapEvent(identity, "Shopify Order Reverted", {
                "Order_ID": readableOrderNumber,
                "Points_Returned": pointsToReturn,
                "Points_Revoked": pointsToRevoke
            }, shop);
        }
    } catch (error) {
        console.error("❌ [REVERT ERROR]", error.message);
    }
}

// ----------------------------------------------------
  // 4. CASE: CHECKOUTS_UPDATE (Discount Removal Logic)
  // ----------------------------------------------------
  // else if (topic === "CHECKOUTS_UPDATE" || topic === "checkouts/update") {
  //   const appliedDiscounts = payload.discount_codes || [];
    
  //   // Check karein ki kya koi REWARD- code abhi checkout mein hai
  //   const hasRewardDiscount = appliedDiscounts.some(d => d.code.startsWith("REWARD-"));

  //   if (!hasRewardDiscount && customerIdString) {
  //     console.log(`🔍 [CHECKOUT] Reward discount removed/not found for Customer: ${customerIdString}`);
      
  //     try {
  //       // Shopify Admin mein wahi discount dhoondo jo remove hua hai
  //       const searchTitle = `REWARD-${customerIdString}`;
  //       const response = await admin.graphql(
  //         `#graphql
  //         query FindDiscount($query: String!) {
  //           discountNodes(first: 5, query: $query) {
  //             edges {
  //               node {
  //                 id
  //                 discount {
  //                   ... on DiscountCodeBasic { title }
  //                 }
  //               }
  //             }
  //           }
  //         }`,
  //         { variables: { query: `title:${searchTitle}*` } }
  //       );

  //       const data = await response.json();
  //       const targetDiscount = data.data?.discountNodes?.edges?.find(e => 
  //         e.node.discount?.title?.startsWith(searchTitle)
  //       );

  //       if (targetDiscount) {
  //         const discountId = targetDiscount.node.id;
  //         console.log(`🗑️ [DELETE] Removing Price Rule ID: ${discountId} from Shopify Admin`);

  //         // Shopify Admin se permanently delete karein
  //         const deleteMutation = `#graphql
  //           mutation discountCodeDelete($id: ID!) {
  //             discountCodeDelete(id: $id) {
  //               deletedCodeDiscountId
  //               userErrors { field message }
  //             }
  //           }
  //         `;

  //         await admin.graphql(deleteMutation, { variables: { id: discountId } });
  //         console.log("✅ [SUCCESS] Abandoned discount deleted.");
  //       }
  //     } catch (err) {
  //       console.error("❌ [CHECKOUT ERROR]", err.message);
  //     }
  //   }
  // }

  else if (topic === "CHECKOUTS_UPDATE" || topic === "checkouts/update") {
  const appliedDiscounts = payload.discount_codes || [];
  // 1. Check karein ki kya koi REWARD- code checkout se HATA diya gaya hai
  const hasRewardDiscount = appliedDiscounts.some(d => d.code.startsWith("REWARD-"));
  if (!hasRewardDiscount && customerIdString) {
    const searchTitle = `REWARD-${customerIdString}`;
    try {
      // 2. Shopify Admin me check karein ki kya wo code abhi bhi exist karta hai
      const response = await admin.graphql(
        `#graphql
        query FindDiscount($query: String!) {
          discountNodes(first: 1, query: $query) {
            edges {
              node {
                id
                discount {
                  ... on DiscountCodeBasic { title }
                }
              }
            }
          }
        }`,
        { variables: { query: `title:${searchTitle}*` } }
      );

      const data = await response.json();
      const node = data.data?.discountNodes?.edges[0]?.node;

      if (node) {
        const discountId = node.id;
        console.log(`🗑️ [REMOVING] Customer manually removed discount: ${node.discount.title}`);
        // 3. Delete Mutation
        const deleteMutation = `#graphql
          mutation deleteDiscount($id: ID!) {
            discountCodeDelete(id: $id) {
              deletedCodeDiscountId
              userErrors { field message }
            }
          }
        `;

        const delRes = await admin.graphql(deleteMutation, { variables: { id: discountId } });
        const delData = await delRes.json();

        if (delData.data?.discountCodeDelete?.deletedCodeDiscountId) {
          console.log("✅ [CLEANUP] Abandoned discount deleted from Admin.");
        } else {
          console.log("⚠️ [USER ERRORS]", delData.data.discountCodeDelete.userErrors);
        }
      }
    } catch (err) {
      console.error("❌ [WEBHOOK ERROR]", err.message);
    }
  }
}
  return new Response();
};